### ISSUE TITLE
"Blog" missing from navigation on blog.synereo.com subdomain

### ISSUE THREAD

**Issue by eeik** [synereo/blog.synereo.com#4]
While viewing the blog at http://blog.synereo.com/, the navigation between the blog and the bare synereo.com domain site does not match. The "BLOG" link is missing while viewing the blog. Additionally, when viewing the blog after an appropriate link is inserted, a highlighted or emphasized indicator on the "BLOG" link itself should be added. This is commonly called out as an "active link" to indicate to the user where within the navigation options they are presently exploring.

At the moment, the link is not present nor noted as "active".

Step 1: Add "BLOG" link mirroring the navigation from the bare Synereo.com domain
Step 2: Ensure it switches state as "Active" when viewing the blog to inform the user of where they are in the navigation

**Comment by lapin7** [comment]
I don't really get what your saying. There's a link from Synereo.com to the Blog.
And the Blog link itself is missing on the Blog header.
The Home link on the Blog page is not linking to Synereo.com
The Blog is becoming very long. It needs an index.

**Comment by eeik** [comment]
Correct on all points, yes. I've updated my initial comment for additional clarity. I can illustrate if need but believe this should be more clear.

**Comment by Elokane** [comment]
Like
