### ISSUE TITLE
Blog wrong update

### ISSUE THREAD

**Issue by lapin7** [synereo/blog.synereo.com#7]
The Blog misses the last HOA of Feb10. It needs a new update. It has to do with frequent updates for getting the links correct.

**Comment by Elokane** [comment]
Fixed. TY

**Comment by lapin7** [comment]
Wonderful. What a collaboration :+1: 
I've installed Jekyll. Got it running. But how do I see the whole site locally on:
http://127.0.0.1:4000/
Only the home page works. All url's link to http://synereo.com

**Comment by lapin7** [comment]
I can see the pages by filling out the whole path like
http://127.0.0.1:4000/2016/02/03/Synereo-Update/

So it's fine now.

**Comment by Elokane** [comment]
(y)
