### ISSUE TITLE
Navigation text decoration required for active link

### ISSUE THREAD

**Issue by eeik** [synereo/blog.synereo.com#9]
I've made a few updates to ensure the [ synereo.com ] and [ blog.synereo.com ] headers are in alignment from a link and target behavior perspective.

It would be nice to rewrite the header such that each page passes along a page reference to dynamically decorate the text on the navigation to help users orient themselves within the site however.

See attached as example to implement.

<img width="796" alt="updates to header css" src="https://cloud.githubusercontent.com/assets/5521252/13175937/ef430366-d772-11e5-8763-ee000daf8bc8.png">

**Comment by CMsynereo** [comment]
Excellent proposal. Do you have access to implement it?
@lapin7
@cm

**Comment by eeik** [comment]
Closing out old orphaned bugs from previous projects.
